### ISSUE TITLE
Can't inject using machobot

### ISSUE THREAD

**Issue by m1entus** [rodionovd/machobot#2]
When i am trying inject dylib i am getting error:

```
MacBook-Pro$ inject_dylib ewqeqw "~/Downloads/some.dylib" 
Traceback (most recent call last):
  File "/usr/local/bin/inject_dylib", line 9, in <module>
    load_entry_point('machobot==0.1.2', 'console_scripts', 'inject_dylib')()
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 2682, in load_entry_point
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 2355, in load
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 2361, in resolve
  File "/Library/Python/2.7/site-packages/machobot/command_line.py", line 10, in <module>
    import machobot.dylib as dylib
  File "/Library/Python/2.7/site-packages/machobot/dylib.py", line 15, in <module>
    from .common.macho_helpers import modify_macho_file_headers
ImportError: No module named common.macho_helpers
```

Any help ?

**Comment by rodionovd** [comment]
Oooops, that's my fault, sorry! I'll fix it ASAP.

Thanks for letting me know about the problem! :green_heart:

**Comment by rodionovd** [comment]
@m1entus please check the new version _(0.1.5)_ out and see if the problem is still there.   

I think you could just uninstall and install it again with pip:

``` bash
$ sudo -H pip uninstall machobot
$ sudo -H pip install --no-cache-dir machobot
```

Thanks!

**Comment by m1entus** [comment]
Thanks, work like a charm!
